controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# api/config/routes.yaml
auth:
    path: /auth
    methods: ['POST']

app_user_by_id:
    path: api/users/{id}
    controller: 'App\Controller\UserController::showProfile'
    methods: ['GET']
#    defaults:
#        _api_resource_class: 'App\Entity\User'
#        _api_item_operation_name: 'get'
