api_platform:
    resource: .
    type: api_platform
    prefix: /api
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    defaults:
        serialization:
            groups: ['Default']