api_platform:
    resource: .
    type: api_platform
    prefix: /api
#    swagger:
#        version: [3]
#    swagger:
#        api_keys:
#            JWT:
#                name: Authorization
#                type: header
#    mapping:
#        paths: ['%kernel.project_dir%/src/Entity']
#    defaults:
#        serialization:
#            groups: ['Default']
