api_platform:
    resource: .
    type: api_platform
    prefix: /api
    patch_formats:
        json: [ 'application/merge-patch+json' ]
#    swagger:
#        version: [3]
#    swagger:
#        api_keys:
#            JWT:
#                name: Authorization
#                type: Header
#    mapping:
#        paths: ['%kernel.project_dir%/src/Entity']
#    defaults:
#        serialization:
#            groups: ['Default']
